import { SelectDefData } from '../types';
import { stringifySelectDef } from './parser';

const escapeAutoItString = (str: string) => {
  return str.replace(/"/g, '""');
};

export const generateAutoItScript = (data: SelectDefData): string => {
  // Convert char array to AutoIt Array string
  let charArrayStr = "Global $aCharacters[1][5] ; Name, Stage, Order, Music, ID\n";
  charArrayStr += `ReDim $aCharacters[${data.characters.length + 1}][5]\n`;
  charArrayStr += `$aCharacters[0][0] = ${data.characters.length}\n`; // 0 index holds count
  
  data.characters.forEach((c, idx) => {
      const i = idx + 1;
      charArrayStr += `$aCharacters[${i}][0] = "${escapeAutoItString(c.name)}"\n`;
      charArrayStr += `$aCharacters[${i}][1] = "${escapeAutoItString(c.stage || '')}"\n`;
      charArrayStr += `$aCharacters[${i}][2] = "${c.order || 1}"\n`;
      charArrayStr += `$aCharacters[${i}][3] = "${escapeAutoItString(c.music || '')}"\n`;
  });

  const optionsStr = `Global $sVictoryMusic = "${escapeAutoItString(data.options.musicVictory || '')}"\n` + 
                     `Global $sArcadeMax = "${data.options.arcadeMaxBattles || 0}"\n` +
                     `Global $sTeamMax = "${data.options.teamMaxBattles || 0}"\n`;

  const extraStagesStr = `Global $sExtraStages = "${data.extraStages.join('|')}"\n`;

  return `; =================================================================================================
; IKEMEN Go Select Editor - Enhanced AutoIt Port
; Generated by Web Editor
; Features: Tabs, List View, Character Management
; =================================================================================================
#include <GUIConstantsEx.au3>
#include <WindowsConstants.au3>
#include <EditConstants.au3>
#include <FileConstants.au3>
#include <MsgBoxConstants.au3>
#include <GuiListView.au3>
#include <GuiTab.au3>
#include <Array.au3>

; Global Data
${charArrayStr}
${optionsStr}
${extraStagesStr}

Global $hGUI = GUICreate("IKEMEN Select Editor (AutoIt Ultimate)", 900, 650)
Global $hTab = GUICtrlCreateTab(10, 10, 880, 580)

; --- Tab 1: Roster Grid (ListView) ---
Global $hTabItem1 = GUICtrlCreateTabItem("Roster Grid")
Global $hListView = GUICtrlCreateListView("Name|Stage|Order|Music", 20, 45, 860, 500)
_GUICtrlListView_SetColumnWidth($hListView, 0, 200)
_GUICtrlListView_SetColumnWidth($hListView, 1, 250)
_GUICtrlListView_SetColumnWidth($hListView, 2, 50)
_GUICtrlListView_SetColumnWidth($hListView, 3, 250)

; Populate ListView from Array (Optimized)
For $i = 1 To $aCharacters[0][0]
    GUICtrlCreateListViewItem($aCharacters[$i][0] & "|" & $aCharacters[$i][1] & "|" & $aCharacters[$i][2] & "|" & $aCharacters[$i][3], $hListView)
Next

Global $idBtnAdd = GUICtrlCreateButton("Add Character", 20, 555, 120, 25)
Global $idBtnEdit = GUICtrlCreateButton("Edit Selected", 150, 555, 120, 25)
Global $idBtnDel = GUICtrlCreateButton("Delete Selected", 280, 555, 120, 25)
Global $idBtnMoveUp = GUICtrlCreateButton("Move Up", 420, 555, 80, 25)
Global $idBtnMoveDown = GUICtrlCreateButton("Move Down", 510, 555, 80, 25)


; --- Tab 2: Global Options ---
Global $hTabItem2 = GUICtrlCreateTabItem("Global Options")
GUICtrlCreateLabel("Victory Music Path:", 40, 60, 150, 20)
Global $idInpVicMusic = GUICtrlCreateInput($sVictoryMusic, 200, 55, 400, 25)
Global $idBtnBrowseMusic = GUICtrlCreateButton("Browse", 610, 55, 80, 25)

GUICtrlCreateLabel("Arcade Max Matches:", 40, 100, 150, 20)
Global $idInpArcade = GUICtrlCreateInput($sArcadeMax, 200, 95, 400, 25)

GUICtrlCreateLabel("Team Max Matches:", 40, 140, 150, 20)
Global $idInpTeam = GUICtrlCreateInput($sTeamMax, 200, 135, 400, 25)

GUICtrlCreateLabel("Extra Stages (Pipe | separated):", 40, 180, 200, 20)
Global $idInpStages = GUICtrlCreateEdit($sExtraStages, 40, 200, 800, 300, BitOR($ES_AUTOVSCROLL, $WS_VSCROLL, $ES_WANTRETURN))


; --- Tab 3: Raw Output Preview ---
Global $hTabItem3 = GUICtrlCreateTabItem("Raw Preview")
Global $idRawEdit = GUICtrlCreateEdit("", 20, 45, 860, 530, BitOR($ES_READONLY, $WS_VSCROLL, $ES_AUTOVSCROLL))
GUICtrlSetFont($idRawEdit, 9, 400, 0, "Consolas")

GUICtrlCreateTabItem("") ; End Tabs

; Footer
Global $idBtnGenerate = GUICtrlCreateButton("Export select.def", 750, 600, 140, 40)
Global $idBtnRefreshRaw = GUICtrlCreateButton("Refresh Preview", 600, 600, 140, 40)

GUISetState(@SW_SHOW)

While 1
    $nMsg = GUIGetMsg()
    Switch $nMsg
        Case $GUI_EVENT_CLOSE
            Exit

        Case $idBtnAdd
            Local $sName = InputBox("New Character", "Enter Character Name (e.g., kfm):", "randomselect")
            If $sName <> "" Then
                GUICtrlCreateListViewItem($sName & "||1|", $hListView)
            EndIf

        Case $idBtnDel
            _GUICtrlListView_DeleteItemsSelected($hListView)

        Case $idBtnGenerate
            Local $sOut = _GenerateDefContent()
            Local $sSavePath = FileSaveDialog("Save Select.def", @ScriptDir, "DEF Files (*.def)", 16, "select.def")
            If $sSavePath <> "" Then
                Local $hFile = FileOpen($sSavePath, 2)
                FileWrite($hFile, $sOut)
                FileClose($hFile)
                MsgBox(0, "Success", "File saved successfully.")
            EndIf

        Case $idBtnRefreshRaw, $hTab
             ; If user clicks tab 3 or refresh button
             If GUICtrlRead($hTab) = 2 Or $nMsg = $idBtnRefreshRaw Then
                 GUICtrlSetData($idRawEdit, _GenerateDefContent())
             EndIf
             
    EndSwitch
WEnd

Func _GenerateDefContent()
    Local $sContent = "; Generated by AutoIt Editor" & @CRLF & @CRLF & "[Characters]" & @CRLF
    Local $iCount = _GUICtrlListView_GetItemCount($hListView)
    
    For $i = 0 To $iCount - 1
        Local $aTxt = _GUICtrlListView_GetItemTextArray($hListView, $i)
        Local $sLine = $aTxt[1] ; Name
        If $aTxt[2] <> "" Then $sLine &= ", stage=" & $aTxt[2]
        If $aTxt[3] <> "1" And $aTxt[3] <> "" Then $sLine &= ", order=" & $aTxt[3]
        If $aTxt[4] <> "" Then $sLine &= ", music=" & $aTxt[4]
        $sContent &= $sLine & @CRLF
    Next
    
    $sContent &= @CRLF & "[ExtraStages]" & @CRLF
    Local $sRawStages = GUICtrlRead($idInpStages)
    $sContent &= StringReplace($sRawStages, "|", @CRLF) & @CRLF
    
    $sContent &= @CRLF & "[Options]" & @CRLF
    $sContent &= "arcade.maxmatches = " & GUICtrlRead($idInpArcade) & @CRLF
    $sContent &= "team.maxmatches = " & GUICtrlRead($idInpTeam) & @CRLF
    If GUICtrlRead($idInpVicMusic) <> "" Then
        $sContent &= "musicvictory = " & GUICtrlRead($idInpVicMusic) & @CRLF
    EndIf
    
    Return $sContent
EndFunc
`;
};
